# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rest_api
    ports:
      - "5432:5432"
  
  redis:
    image: "redis:latest"
    ports: 
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
